config/routes.rb
Grocery::Application.routes.draw do
  root to: "lists#index"
  resources :lists, only: [:index, :create] do
    resources :items, only: [:index, :create, :destroy]
  end
end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :list_id, :name
  validates :name, :list_id, presence: true

  def self.for_list(list_id)
    where(list_id: list_id)
  end
end

app/models/list.rb
class List
  def to_param
    SecureRandom.urlsafe_base64
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.for_list(params[:list_id])

    respond_to do |format|
      format.html
      format.json { render json: @items }
    end
  end

  def create
    @item = Item.create(params[:item])
    redirect_to list_items_url
  end

  def destroy
    Item.find_by_list_id_and_id(params[:list_id], params[:id]).destroy
    redirect_to list_items_url
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
  end

  def create
    list = List.new
    redirect_to list_items_url(list)
  end
end

app/views/items/_form.html.haml
= form_for @item do |f|
  - if @item.errors.any?
    #error_explanation
      %h2= "#{pluralize(@item.errors.count, "error")} prohibited this item from being saved:"
      %ul
        - @item.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :list_id
    = f.text_field :list_id
  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/items/edit.html.haml
%h1 Editing item

= render 'form'

= link_to 'Show', @item
\|
= link_to 'Back', items_path

app/views/items/index.html.haml
= form_for Item.new, url: list_items_url(params[:list_id]) do |f|
  = f.text_field :name, placeholder: "Name"
  = f.hidden_field :list_id, value: params[:list_id]
  = f.submit "Add", class: "btn btn-primary"

- if @items.present?
  .items
    - @items.each do |item|
      .item.clearfix
        = link_to "Delete", list_item_url(params[:list_id], item), method: :delete, class: "btn btn-danger btn-small"
        %p= item.name

app/views/items/new.html.haml
%h1 New item

= render 'form'

= link_to 'Back', items_path

app/views/items/show.html.haml
%p#notice= notice

%p
  %b List:
  = @item.list_id
%p
  %b Name:
  = @item.name

= link_to 'Edit', edit_item_path(@item)
\|
= link_to 'Back', items_path

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no")
    %meta(name="apple-mobile-web-app-capable" content="yes")
    %meta(name="apple-mobile-web-app-status-bar-style" content="black-translucent")
    %title= content_for?(:title) ? yield(:title) : "Grocery"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag "apple-touch-icon-144x144.png", rel: "apple-touch-icon", sizes: "144x144", type: "image/png"
    = favicon_link_tag "apple-touch-icon-72x72.png", rel: "apple-touch-icon", sizes: "72x72", type: "image/png"
    = favicon_link_tag "apple-touch-icon.png", rel: "apple-touch-icon", type: "image/png"
    = favicon_link_tag "/favicon.png", rel: "shortcut icon", type: "image/png"

  %body
    .navbar.navbar-top
      .navbar-inner
        .container
          = link_to root_url, class: "brand" do
            %i.icon-shopping-cart
            Brando's Grocery List

    .container-fluid= yield
    = yield(:js).presence
    = javascript_include_tag "application"

app/views/lists/index.html.haml
= button_to "New List", lists_url, class: "btn btn-large btn-primary"